### ISSUE TITLE
Code Example

### ISSUE THREAD

**Issue by sanojb99** [ricklupton/floweaver#103]
Does the code for Fig7 of your paper exist somewhere as an example?

Lupton, R.C., and J.M. Allwood. 2017. ‘Hybrid Sankey Diagrams: Visual Analysis of Multidimensional Data for Understanding Resource Use’. Resources, Conservation and Recycling 124 (September): 141–51. https://doi.org/10.1016/j.resconrec.2017.05.002.

**Comment by sanojb99** [comment]
Found it! Sorry :)
https://floweaver.readthedocs.io/en/latest/cookbook/hybrid-sankey-diagrams-paper-fruit-example.html

**Comment by ricklupton** [comment]
Glad you found it! Hope it helps.
