### ISSUE TITLE
Define size in SankeyWidget()

### ISSUE THREAD

**Issue by sanojb99** [ricklupton/floweaver#104]
Hello,

is it possible to define the size of the output image within `SankeyWidget()`?

I tried two ways which are both not working.
```
SankeyWidget(
    layout=Layout(height='1000', width='600),
    links=flows.to_dict('records')
            )
```
and
```
SankeyWidget(
    size = dict(width=1000, height=600),
    links=flows.to_dict('records')
            )
```

**Comment by ricklupton** [comment]
That should work. The first example is how floweaver does it ([see here](https://github.com/ricklupton/floweaver/blob/master/floweaver/sankey_data.py#L91)) though you have a missing `'` in your example. 

Are you trying to change the size within the notebook, or when saving as a png or svg?

**Comment by sanojb99** [comment]
Thank you very much for your prompt response!

I am trying to change the size when saving as png or svg.

SankeyWidget(
    layout=Layout(height='1000', width='600'),
    links=flows.to_dict('records')
            ).auto_save_svg('{}/quickstart_example1.svg'.format(output_path))
            
However, I still receive the following error:

![grafik](https://user-images.githubusercontent.com/51230596/105157986-c7387300-5b0d-11eb-8e5e-11dd13d97daf.png)

**Comment by ricklupton** [comment]
You need to import `Layout`. Look at the top of the file I linked.

**Comment by sanojb99** [comment]
Ahh :) I see. Now it's working. Thank you very much for your support and the great Python package!
