### ISSUE TITLE
Use floweaver in loop

### ISSUE THREAD

**Issue by sanojb99** [ricklupton/floweaver#109]
Hello and thank you for your great package!
Can anyone hint me in the right direction why floweaver does not generate output in a loop?
Thank you!

```Python
import pandas as pd
from ipysankeywidget import SankeyWidget

flows = pd.read_csv(
    'simple_fruit_sales.csv'
)

for i in flows['source']:

    SankeyWidget(links=flows.to_dict('records')).auto_save_png('{}.png'.format(i))

```

**Comment by ricklupton** [comment]
Duplicate of https://github.com/ricklupton/ipysankeywidget/issues/17, I think -- hope that helps.

**Comment by sanojb99** [comment]
Works! :) Thanks!
