### ISSUE TITLE
How to extend the length of texts for the target column?

### ISSUE THREAD

**Issue by mpouyakh9** [ricklupton/floweaver#114]
Hi,

Thank you very much for developing this libarary. It is very helpful, however I have a issue with the length of texts for target column. When it exceeds a certian limit the texts is choped off and not shown anymore. How can I set the length to be able to have desired length of text? 

Here below in the figure you can see some of the texts like first, second and one before last one are cut and incomplete.
![github](https://user-images.githubusercontent.com/71394600/123291478-239a2700-d4e0-11eb-972f-30d09cd0462d.png)

**Comment by ricklupton** [comment]
Try to increase the right margin — see the tutorials for an example.

**Comment by mpouyakh9** [comment]
Thanks
