### ISSUE TITLE
Order of nodes

### ISSUE THREAD

**Issue by BinglingICL** [ricklupton/floweaver#120]
Is there a way to set the order of nodes in the way we want, rather than the alphabetical order? Many thanks!

**Comment by ricklupton** [comment]
Hi @BinglingICL, yes, you can set this in two places:
- The [ordering](https://floweaver.readthedocs.io/en/latest/sdd.html#floweaver.SankeyDefinition) property of the `SankeyDefinition` if your nodes are separate `ProcessGroup`s or `Waypoints`
- The order of the [Partition](https://floweaver.readthedocs.io/en/latest/sdd.html#floweaver.ProcessGroup.partition) given to the `ProcessGroup` if those are the nodes you are trying to adjust.

Does that help?

**Comment by BinglingICL** [comment]
Hi @ricklupton, thanks very much for your hints. This is very helpful. Yes, I have done it within 'Partition'!
