### ISSUE TITLE
how to save a sankey diagram

### ISSUE THREAD

**Issue by krrome** [ricklupton/floweaver#2]
Hi,
I decided to ask this question as an issue, since I feel like this is missing in your tutorial. After hours of playing around I haven't figured out how to generate a png / svg etc. I tried to use `show_sankey` without using a ipython notebook, but the image strings are not generated. Is there a way to save the plot to a file (not only the json description with `save_sankey_data`)? Alternatively do you have some code to generate json data that is compatible with your d3 plugin?
Thank you,
Roman

**Comment by ricklupton** [comment]
The easiest way is to use `show_sankey` in a Jupyter notebook. Have you seen these examples from ipysankeywidget? http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/Exporting%20Images.ipynb

Using `show_sankey` outside the notebook won't work -- it relies on IPython widgets to render the diagram in the browser and send back the png/svg.

Another way is to save the data as a JSON file then use e.g. [svg-sankey](https://github.com/ricklupton/svg-sankey) to convert it to SVG using the d3 plugin. The documentation for that is out of date as the d3 plugin and the JSON format have been evolving over the last few months, so we should review that.

**Comment by krrome** [comment]
sorry for the late reply.. thank you, I went with the jupiter notebook solution.
