### ISSUE TITLE
Prevent installation on Python 2

### ISSUE THREAD

**Issue by rodelius** [ricklupton/floweaver#23]
After successful (pip) installation (v2.0.0a3) I tried importing the floweaver module but got the following error. Also tried an earlier version but same error. 

Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import floweaver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mr/anaconda2/lib/python2.7/site-packages/floweaver/__init__.py", line 13, in <module>
    from .color_scales import CategoricalScale, QuantitativeScale
  File "/Users/mr/anaconda2/lib/python2.7/site-packages/floweaver/color_scales.py", line 59
    raise ValueError('No qualitative palette called {}'.format(palette)) from None
                                                                            ^
SyntaxError: invalid syntax

**Comment by ricklupton** [comment]
Hi, thanks for getting in touch. floWeaver doesn't officially support Python 2 -- can you use Python 3? If so that's the way to go

If not it shouldn't be too hard to make it run on Python 2 as well -- probably not a priority unless it's an issue for lots of people, but contributions welcome!

**Comment by rodelius** [comment]
Ok thanks Rick I missed the python 3 requirement. I will have another go at it.

Kind regards,
Martin.

Skickat från min iPhone

**Comment by ricklupton** [comment]
Did you get it working on Python 3? I'll leave this issue open as a reminder to try to give a warning or prevent installation on Python 2.

**Comment by rodelius** [comment]
Hi Rick,

Thanks for coming back to me. Yes python 3 install worked fine. 

Sounds like good idea to get warning or similar to alert user trying to run on python 2.

Kind regards,
Martin.

Skickat från min iPhone

**Comment by Nemecsek** [comment]
Hi Rick.
It is actually an issue for me (old code that I can not move easily to Python 3). 
Is there anybody working on Python 2 compatibility?

BTW, https://pypi.python.org/pypi/floweaver/2.0.0a3 states that it is Python 2 compatibile...
