### ISSUE TITLE
Saving Sankey to image?

### ISSUE THREAD

**Issue by Nemecsek** [ricklupton/floweaver#26]
I want to use it outside jupyter, if possible: I would like to create offline the sankey and then import in my page only the final image (JPG/SVG). 
Is this possible?

**Comment by ricklupton** [comment]
Yes you can export to png & svg. There is an example in cell 8 of the [quickstart tutorial](https://floweaver.readthedocs.io/en/latest/tutorials/quickstart.html): use the `auto_save_png(filename)` and `auto_save_svg(filename)` methods of [`ipysankeywidget`](http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/Exporting%20Images.ipynb)

**Comment by ricklupton** [comment]
This should be explicitly discussed in the floWeaver docs though.

**Comment by eotp** [comment]
Is there a way to specify the dpi/output quality when using `auto_save_png(filename)`? 
e.g. `auto_save_png(filename, dpi = 600)`

**Comment by JFA-CT** [comment]
I am also interested in saving the diagram to a higher quality jpeg or png. I've looked extensively in the documents. Did you come right? Any tips would be helpful. thank you!

**Comment by Nemecsek** [comment]
@JFA-CT, Alas I abandoned the project long time ago and cannot help you. Sorry.
