### ISSUE TITLE
Remove claim to Python 2 compatibility

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/floweaver#27]
The package metadata is currently saying it is Python 2 compatible, but it isn't. This needs fixing in `setup.py`:

https://github.com/ricklupton/floweaver/blob/master/setup.py#L42-L43

**Comment by dnuka** [comment]
Hi! I would like to have this assigned to me for the MozSprint.

**Comment by ricklupton** [comment]
Merged in #39
