### ISSUE TITLE
"Could not instantiate widget error" on Azure Notebooks

### ISSUE THREAD

**Issue by simon-ritchie** [ricklupton/floweaver#29]
I encountered "Could not instantiate widget error" when running python script on Azure Notebooks.

Environment :

- Python 3.5.4,  and same result at Python 3.6
- floweaver-2.0.0a3 palettable-3.1.0
- ipysankeywidget-0.2.4 ipywidgets-7.2.1 widgetsnbextension-3.2.1
- Browser : Google Chrome

code :

```py3
!jupyter nbextension enable --py --sys-prefix ipysankeywidget
```

```
Enabling notebook extension jupyter-sankey-widget/extension...
      - Validating: OK
```

```
!jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

```
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
```

```py3
import pandas as pd
flow_df = pd.DataFrame(
    columns=['source', 'target', 'type', 'value'],
    data=[{'source': 'farm1', 'target': 'Mary', 'type': 'apples', 'value': 5},
          {'source': 'farm1', 'target': 'James', 'type': 'apples', 'value': 3},
          {'source': 'farm2', 'target': 'Fred', 'type': 'apples', 'value': 10},
          {'source': 'farm2', 'target': 'Fred', 'type': 'bananas', 'value': 10},
          {'source': 'farm2', 'target': 'Susan', 'type': 'bananas', 'value': 5},
          {'source': 'farm3', 'target': 'Susan', 'type': 'apples', 'value': 10},
          {'source': 'farm4', 'target': 'Susan', 'type': 'bananas', 'value': 1},
          {'source': 'farm5', 'target': 'Susan', 'type': 'bananas', 'value': 1},
          {'source': 'farm6', 'target': 'Susan', 'type': 'bananas', 'value': 1}])

from floweaver import ProcessGroup, Bundle, SankeyDefinition, weave
size = {'width': 570, 'height': 300}

nodes = {
    'farms': ProcessGroup(['farm1', 'farm2', 'farm3', 'farm4', 'farm5', 'farm6']),
    'customers': ProcessGroup(['James', 'Mary', 'Fred', 'Susan']),
}

ordering = [
    ['farms'],
    ['customers'],
]

bundles = [
    Bundle('farms', 'customers'),
]

sdd = SankeyDefinition(nodes=nodes, bundles=bundles, ordering=ordering)
weave_ = weave(sankey_definition=sdd, dataset=flow_df)

# When this code run, error dislayed on browser console.
weave_.to_widget(**size, debugging=True)
```

<img width="736" alt="20180422_1" src="https://user-images.githubusercontent.com/25178045/39092371-46bbf356-4647-11e8-883d-adb9f98a461a.png">

**Comment by ricklupton** [comment]
Hi,

Thanks for reporting this. I've tried reproducing it in a local environment (see below) but it works for me. I wonder if it could be due to activating the widgets from within the notebook after the Jupyter notebook app is already loaded and running on Azure. Is there an option to run the `jupyter nbextension enable` commands as part of your environment setup, before starting the notebook, or to run then then shutdown and restart the notebook app?

Can you use other core widgets (e.g. ipywidgets.Slider) and other custom widgets (e.g. Leaflet) in your Azure notebooks?

```shell
$ /usr/bin/python3.6 -m venv testenv
$ source testenv/bin/activate
$ pip install floweaver==2.0.0a3 palettable==3.1.0 ipysankeywidget==0.2.4 ipywidgets==7.2.1 widgetsnbextension==3.2.1
[...]
Successfully installed MarkupSafe-1.0 Send2Trash-1.5.0 attrs-17.4.0 backcall-0.1.0 bleach-2.1.3 decorator-4.3.0 entrypoints-0.2.3 floweaver-2.0.0a3 html5lib-1.0.1 ipykernel-4.8.2 ipysankeywidget-0.2.4 ipython-6.3.1 ipython-genutils-0.2.0 ipywidgets-7.2.1 jedi-0.12.0 jinja2-2.10 jsonschema-2.6.0 jupyter-client-5.2.3 jupyter-core-4.4.0 mistune-0.8.3 nbconvert-5.3.1 nbformat-4.4.0 networkx-1.11 notebook-5.4.1 numpy-1.14.2 palettable-3.1.0 pandas-0.22.0 pandocfilters-1.4.2 parso-0.2.0 pexpect-4.5.0 pickleshare-0.7.4 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pygments-2.2.0 python-dateutil-2.7.2 pytz-2018.4 pyzmq-17.0.0 simplegeneric-0.8.1 six-1.11.0 terminado-0.8.1 testpath-0.3.1 tornado-5.0.2 traitlets-4.3.2 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.2.1
$ python -m ipykernel install --user --display-name "Python test" --name test3
Installed kernelspec test3 in /home/rick/.local/share/jupyter/kernels/test3
$ jupyter notebook
```

**Comment by simon-ritchie** [comment]
Hi, ricklupton.
Thanks for reply.

> or to run then then shutdown and restart the notebook app?

I tested that, but same error occurred.

> Is there an option to run the jupyter nbextension enable commands as part of your environment setup

Possibly there is options to solve this, but currently I found nothing.

> Can you use other core widgets (e.g. ipywidgets.Slider) and other custom widgets (e.g. Leaflet) in your Azure notebooks?

Yes, core widgets works correctly.

---

According to the Azure Notebooks github repository and stackoverflow, probably this is Azure Notebooks problem, so I close this issue. 
I hope Azure Notebooks fix this and can use.

- [Custom ipywidgets fail to load properly](https://github.com/Microsoft/AzureNotebooks/issues/194)

>  I guess that notebooks.azure.com doesnt support 3rd party widgets
> [Unable to get custom ipywidget working on notebooks.azure.com
](https://stackoverflow.com/questions/46583268/unable-to-get-custom-ipywidget-working-on-notebooks-azure-com)

thx.

**Comment by ricklupton** [comment]
That's a shame you can't use custom widgets on Azure Notebooks. Let us know if you find a solution!
