### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/floweaver#30]
Here are some welcome (but easy!) contributions:

- ["ipywidets"](https://github.com/ricklupton/floweaver#get-started-using-floweaver)
- Add link forwards to citation details at end of [first section where it says "see below"](https://github.com/ricklupton/floweaver#floweaver)

**Comment by dnuka** [comment]
Hi! I would like to have this assigned to me for the MozSprint.

**Comment by dnuka** [comment]
Hi @ricklupton Thank you very much for being supportive.

**Comment by ricklupton** [comment]
Merged -- thanks for your help :tada: 

If you fancy having a go at any other issues do have a look and let me know if you have any questions.
