### ISSUE TITLE
We'd like a logo!

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/floweaver#32]
Something like this perhaps? With the lines below meant to suggest a Sankey diagram.

![logo_sketch](https://user-images.githubusercontent.com/878794/39247537-9a6ba996-4891-11e8-8aef-17d415f6be0a.png)

Or better ideas also welcome :grinning:

**Comment by abmakko** [comment]
![floweaver icon-02](https://user-images.githubusercontent.com/36611833/39527625-93a1f93c-4e2a-11e8-976f-c2576965b227.png)

Hello Ricklupton, Good day, I made an Icon for your project based on your Sankey diagram theme.

**Comment by abmakko** [comment]
![flowweaver text-01](https://user-images.githubusercontent.com/36611833/39527742-e4f4ddc2-4e2a-11e8-8bc9-832c9a7f2117.png)
I also made another one based on your text typography Idea

**Comment by abmakko** [comment]
Tell me what you think about the design. I'll be happy to contribute to your project

**Comment by ricklupton** [comment]
Thanks very much! I like them. It's mostly for the website, not for an app icon, so I think the one with the text is probably better.

Two things I think would improve it: I don't like the lined-letter font of the "flo", and I think there's too much contrast between the "flo" and the "weaver". Especially as the W is kind of doubling as the end of floW and the start of Weaver.

As a minor thing, to look like a proper Sankey diagram the curve across the middle should be constant width, and I wasn't sure on first sight about the white gaps around the grey boxes -- but maybe that wouldn't look right.

**Comment by abmakko** [comment]
Okay. I'm attending to your corrections now. I will get back to you in next 5 hours

**Comment by abmakko** [comment]
![flo weaver landscape-02](https://user-images.githubusercontent.com/36611833/39666201-8c0f2f52-50a8-11e8-85d6-aaaaeff3d5f2.png)
![flo weaver landscape-03](https://user-images.githubusercontent.com/36611833/39666202-8c3f658c-50a8-11e8-9bf3-2714368ffad6.png)

**Comment by abmakko** [comment]
Thanks. I made the two adjustments according to your recommendations. you can pick between the two. if there is any further corrections you would like. , let me know and I will respond ASAP. I would like to send you a pull request afterwards.

**Comment by ricklupton** [comment]
Thanks for the updates and sorry for the slow reply. I like this last one. I'll add it to the README and website :+1:

**Comment by ricklupton** [comment]
Nicely decorating the top of the README now! Could you open a PR to add the svg file to the repo (probably in `docs/`) or attach it here, when you get a chance?

**Comment by abmakko** [comment]
Hello. thanks for approving my design. I'm glad that you are pleased with it and already merged with your project. this is the [pull request](https://github.com/ricklupton/floweaver/pull/48) of the SVG file you asked for. here is also a [link](https://drive.google.com/open?id=15IYyDY6tjbKfSRC0msr0b8uFB-CKTv6e) to google drive containing adaptable icons and monochrome versions that you might need in the future and also my raw design files. thanks again :-)

**Comment by ricklupton** [comment]
Thanks again, I added you to the list of contributors.
