### ISSUE TITLE
Make a conda package

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/floweaver#43]
If anyone has experience of building conda packages, or wants to give it a try, it would be great is floWeaver and [ipysankeywidget](https://github.com/ricklupton/ipysankeywidget) could be installed using conda. I think this just involves putting together a conda recipe.

Any questions let me know by replying below or asking in the [chat](https://gitter.im/floweaver/Lobby)!

**Comment by dnuka** [comment]
Hi Rick, I'd love to work on this. I don't know anything about data visualization or building conda packages. But I still love to work on this because, floweaver is the first open source project I contributed to. Is there any special way should I follow or just build the package and upload it to github?

Thanks.

**Comment by ricklupton** [comment]
Hi @dnuka! Great to hear you want to come and work some more on floWeaver :smile: 

I think the steps needed are:
1. Write a conda `meta.yaml` file -- conda has a tutorial about this I think
2. Check it works by building a package yourself and uploading it to anaconda in your own channel
3. Add something to the [developer docs](https://github.com/ricklupton/floweaver/blob/master/DEVELOPING.md) describing how to build the package and upload it to anaconda.
4. I (or whoever is releasing a new version of floWeaver) can then use your instructions and meta file to upload an official version to anaconda.

You can have a look too at [this pull request in ipysankeywidget](https://github.com/ricklupton/ipysankeywidget/pull/33), where @ali-alsabbah is doing something similar for that package.

Let me know if you have any questions, or just have a go and share your progress.

**Comment by ricklupton** [comment]
Ah, sorry, I missed that @ali-alsabbah had also started a `meta.yaml` file for floWeaver too (https://github.com/ricklupton/floweaver/pull/58) -- getting confused between the different repositories! Can you confirm if that's done @ali-alsabbah?

If it's done, similar to my comment in https://github.com/ricklupton/ipysankeywidget/pull/33#issuecomment-420799770 some instructions for developers (e.g. me!) would be very helpful. If not, is there anything @dnuka can help with?

**Comment by Rishabh0712** [comment]
Hi guys. I wanted to know whether this issue is still open or not. If open I would like to work on it.

**Comment by ricklupton** [comment]
Hi @Rishabh0712, thanks for the offer! We have a meta.yaml file contributed here https://github.com/ricklupton/floweaver/pull/58


I think I’m now the bottleneck to try to build a package and upload to conda — I’ll try to do that next week — and until I try I’m not sure what else needs doing. If you would like to test it in the meantime or suggest any changes that would be welcome!

**Comment by cpatz** [comment]
Hey, any update on the conda package? I'd love to experiment with this package as it seems more intuitive than alternative packages for Sankey, however, I'm unable to use pip so a conda package would be my only way to access?

**Comment by ricklupton** [comment]
floweaver and ipysankeywidget are now available through conda-forge!
