### ISSUE TITLE
Display values/weights for partitions in each node

### ISSUE THREAD

**Issue by pgabriel2** [ricklupton/floweaver#53]
Thanks a lot for this great project. I've been using it to display customer flow dynamics and it works like a treat. 

I was wondering if it is possible to display the value for each of the partitions in each node alongside the title? For example in your [Basic diagram example](https://floweaver.readthedocs.io/en/latest/tutorials/quickstart.html#Basic-diagram) I would like to see something like `farms (46)` --> `customers (46)` and the same for each section of the more complicated versions so that the value/weight of the connection is immediately clear. This would be particularly useful when exporting images. 

I can calculate the value/weights and dynamically change the title but was wondering if there is an easier way to do this.

**Comment by ricklupton** [comment]
Hi @pgabriel2 glad you're finding it useful! It's great to hear how people are using floweaver so if you're happy to share it'd be interesting to hear a bit more about what you're doing :)

I'm afraid there isn't currently a built-in way to do this but it would be a great feature to add. Probably it should be added in the underlying Sankey diagram library ipysankeywidget & d3-sankey-diagram, as then it benefits any diagram even if floweaver is not being used to prepare the data. 

Closing this to track in https://github.com/ricklupton/ipysankeywidget/issues/30.
