### ISSUE TITLE
Annotating individual flows lines with values

### ISSUE THREAD

**Issue by pvphaneuf** [ricklupton/floweaver#57]
It would be nice to have a way of annotating individual flow lines, where one could annotate the value represented by a flow line for the sake of presentations.

For instance, annotating a value on each of the lines coming out of "bananas".
![image](https://user-images.githubusercontent.com/4079329/43923337-59607d12-9bd6-11e8-8d46-4b5fca465cfd.png)
Could be very cluttered in the attached example, but simpler diagrams could benefit from the inclusion of the mouse-over values statically annotated on each flow.

**Comment by ricklupton** [comment]
Hi @pvphaneuf, thanks for the suggestion and sorry for the slow reply. I think this is a good idea, but it probably needs to be added as a feature to the underlying `d3-sankey-diagram` library first. I'll create an issue there to track this.

**Comment by ELC** [comment]
A similar feature is already present when one is watching the Sankey online or exported to `svg`, one could see the exact value of the flow hovering the cursor over it (the svg should be open from browser, tested with Chrome 68).

**Comment by ricklupton** [comment]
Thanks for clarifying, yes, mouse-over is already there -- but static labels are also useful in some cases.

**Comment by ricklupton** [comment]
This is nearly possible now -- see #74
