### ISSUE TITLE
[Feature Request]: Vertical Direction 

### ISSUE THREAD

**Issue by Krisselack** [ricklupton/floweaver#69]
Would it be possible to draw a sankey-diagram in vertical direction with floweaver?

**Comment by ricklupton** [comment]
Hi @Krisselack, it's not possible at the moment. You might be able to get it working though by using CSS `transform` rotations on the diagram itself, and then on the text labels to rotate them back to be horizontal? There is an [example in the ipysankeywidget docs](https://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/More%20examples.ipynb#Styling) of using CSS in the notebook.
