### ISSUE TITLE
No figure displayed.

### ISSUE THREAD

**Issue by tianwenzhe098** [ricklupton/floweaver#70]
When I  run the example code, no figure displayed at all.
I'm very interested in that package. Can you solve my problem?
Many thanks
![problem](https://user-images.githubusercontent.com/42595792/50333920-b3427180-0541-11e9-8297-f4dc506e0e13.JPG)

**Comment by ricklupton** [comment]
You need to use it in the Jupyter notebook or use `svg-sankey`, see #34
