### ISSUE TITLE
Use LinkLabel from ipysankeywidget 

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [ricklupton/floweaver#74]
Hi,

I'm generating my graph using the following command:
`sdd = SankeyDefinition(nodes, bundles, ordering,flow_partition=flow_partition)
weave(sdd, flows, palette='Set2_5').to_widget(**size,align_link_types=True)`

However, I would like to have the links labeled as in https://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/More%20examples.ipynb

Is this possible?

**Comment by ricklupton** [comment]
Thanks, good idea -- this isn't an option at the moment but it would make sense to add it as an option to `to_widget` method I think:

https://github.com/ricklupton/floweaver/blob/master/floweaver/sankey_data.py#L60-L81

Perhaps `link_label_format` and `link_label_min_width` keyword arguments that get passed through. Contributions welcome to speed up the process! :)

**Comment by ricklupton** [comment]
Closed by #91
