### ISSUE TITLE
Expand text area

### ISSUE THREAD

**Issue by nbucklin** [ricklupton/floweaver#79]
Hello,

Is there a way to expand the total area of the diagram so that text doesn't get cutoff? I'm having an issue where the text labels for my partitions is being cut off (looks like the limit is 12 characters). You can see it this happening in the *holiday_data.csv* example below. Except that I have many cases which this is happening. Thanks for your help!

![Capture](https://user-images.githubusercontent.com/31641550/56765343-cde95900-6774-11e9-8ba7-fe205b73b5a6.JPG)

**Comment by ricklupton** [comment]
Look at the margin kwargs in the widget options. Let me know if you can’t find what I mean.

**Comment by nbucklin** [comment]
That did the trick! Thanks for your help!
