### ISSUE TITLE
Floweaver/ipysankeywidget rendering in JupyterLab

### ISSUE THREAD

**Issue by PhilCHC** [ricklupton/floweaver#80]
Love the library, I wish I could get it to work in JupyterLab

**Comment by ricklupton** [comment]
Hi, thanks :) It'd be great to get it working in JupyterLab, I just haven't had the time to try yet. Help here is welcome, if anyone is interested!

Closing as duplicate of https://github.com/ricklupton/ipysankeywidget/issues/36
