### ISSUE TITLE
results_graph.py add_node() dependency issue?

### ISSUE THREAD

**Issue by eshowa** [ricklupton/floweaver#81]
Hello, I ran through the fruit sales tutorial on my own notebook and keep running into this. Is it a dependency or environment configuration problem?

Thanks,
esh

sdd = SankeyDefinition(nodes, bundles, ordering)
weave(sdd, flows).to_widget(**size)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-d107ed93fab5> in <module>
      1 sdd = SankeyDefinition(nodes, bundles, ordering)
----> 2 weave(sdd, flows).to_widget(**size)

~/floweaver/floweaver/weave.py in weave(sankey_definition, dataset, measures, link_width, link_color, palette)
     50                                flow_partition=sankey_definition.flow_partition,
     51                                time_partition=sankey_definition.time_partition,
---> 52                                measures=measures)
     53 
     54     # Default link width is same as default measure

~/floweaver/floweaver/results_graph.py in results_graph(view_graph, bundle_flows, flow_partition, time_partition, measures)
     34                                  else 'group'),
     35                         'direction': node.direction,
---> 36                         'title': title,
     37                     })
     38                 groups.append({

TypeError: add_node() takes 2 positional arguments but 3 were given

**Comment by ricklupton** [comment]
Hi, it sounds like it might be the version of networkx -- the latest release needs version 1.x, but the git master version was recently updated (#77) to use version 2.x. Does that help?

**Comment by ricklupton** [comment]
@eshowa I've released a new version (2.0.0a5) which should work with networkx version 2.x now. Can you try installing again with conda or pip (it might take a short time before the new version is picked up) and let me know if you still have any trouble?

**Comment by eshowa** [comment]
Thank you for the advice last email and this update. I will be able to try
these out after next week.

Esther

**Comment by ricklupton** [comment]
I think this is fixed now in the latest version of floweaver.
