### ISSUE TITLE
Problem in Partition.py

### ISSUE THREAD

**Issue by fmichaelkunz** [ricklupton/floweaver#85]
Here is the text of the error message I got on trying to load Floweaver. 
Running Python 3.6.8. updated all packages so they are most current. 
TypeError: attrib() got an unexpected keyword argument 'converter'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-a26feeb46fda> in <module>

---> 13 import floweaver as fw
     14 

~/Python/anaconda/envs/py36env/lib/python3.6/site-packages/floweaver/__init__.py in <module>
      3 __version__ = '2.0.0a5'
      4 
----> 5 from .dataset import Dataset
      6 from .partition import Partition, Group
      7 from .sankey_definition import SankeyDefinition, ProcessGroup, Waypoint, Bundle, Elsewhere

~/Python/anaconda/envs/py36env/lib/python3.6/site-packages/floweaver/dataset.py in <module>
      2 import networkx as nx
      3 
----> 4 from .partition import Partition
      5 
      6 

~/Python/anaconda/envs/py36env/lib/python3.6/site-packages/floweaver/partition.py in <module>
      9 
     10 @attr.s(slots=True, frozen=True)
---> 11 class Group(object):
     12     label = attr.ib(converter=str)
     13     query = attr.ib(converter=tuple, validator=_validate_query)

~/Python/anaconda/envs/py36env/lib/python3.6/site-packages/floweaver/partition.py in Group()
     10 @attr.s(slots=True, frozen=True)
     11 class Group(object):
---> 12     label = attr.ib(converter=str)
     13     query = attr.ib(converter=tuple, validator=_validate_query)
     14 

TypeError: attrib() got an unexpected keyword argument 'converter'

**Comment by ricklupton** [comment]
Hi, do you have an old version of the `attr` package you can update? Looks like "converter" was added as a new name for "convert" a while ago: http://www.attrs.org/en/stable/changelog.html#id54

**Comment by ricklupton** [comment]
Updated the minimum attrs requirement to fix this.
