### ISSUE TITLE
publishable format

### ISSUE THREAD

**Issue by JFA-CT** [ricklupton/floweaver#88]
Hi, 
Thanks for the great package! I'm looking to save the diagrams into a high quality jpeg or png, but I can't seem to add a DPI  to the save_png command. Also, converting an SVG renders an equally poor quality image. Do you have any suggestions? 
Also is there capacity to change fonts? I've not seen any mention of this.
Thanks for any help!

**Comment by ricklupton** [comment]
Hi, it was a long time ago but if it's still useful:

Using `save_svg` or `auto_save_svg` should give you a high quality vector SVG image that you can tweak as required (e.g. to change fonts) and then export to PNG at whatever resolution you want.

You can change fonts in the Jupyter notebook using CSS (see the ["advanced examples"](https://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/More%20examples.ipynb) from ipysankeywidget).
