### ISSUE TITLE
Networkx 2.4

### ISSUE THREAD

**Issue by frankhoogeveen** [ricklupton/floweaver#89]
Just to let you know that I tried to run the quickstart tutorial. With networkx 2.3 installed, it ran without issues. With networkx 2.4 it crashed. 

I'm happy to provide more details if that helps.

**Comment by jAchtzehn** [comment]
Can confirm this. The error has also been reported in [https://github.com/ricklupton/floweaver/issues/90](url).

**Comment by ricklupton** [comment]
Thanks @frankhoogeveen and @jAchtzehn, this is now fixed in floweaver v2.0.0a6 (393defb49fb35184bc65e35687f609853d876b48)
