### ISSUE TITLE
Backwards Flows between nodes

### ISSUE THREAD

**Issue by jfouillou** [ricklupton/floweaver#9]
Hello,

I've been having trouble with handling flows which flow backwards relative to the overall direction of the Sankey. In this case (images below), the general direction is from left to right, but 'utilities' and 'refineries'  exchange flows with each other, so there is inevitably a backwards flow which floweaver does not seem to handle well. Furthermore, floweaver seems to show the wrong direction for the backwards flow (for instance the output of the refinery that goes to the utility is shown as an input to the refinery). I've tried bundling these flows in different ways, but to no avail. Below is included both a screenshot where 'Utilities' and ' Refineries' are in the same horizontal band but a different vertical band, and the reverse. Here's a copy of the code I've used thus far, would you know by any chance how to handle this?

Thank you very much for your help!

![screenshot 2](https://user-images.githubusercontent.com/20640418/36420215-33a912e4-162c-11e8-8197-706364bbc473.png)
![screenshot](https://user-images.githubusercontent.com/20640418/36420217-33c9720a-162c-11e8-8b3a-eb6be5ff29c0.png)

nodes = {
    'Sources': ProcessGroup(['Coal', 'Crude Oil' , 'Gas', 'Solid biomass & waste', 'Renewable','Minerals', 'Scrap', 'Other Materials']),
    'Refineries': ProcessGroup(['Refineries']),
    'Utilities': ProcessGroup(['Utilities']),
    'Industry': ProcessGroup(['Iron and steel', 'Non-ferrous metals', 'Paper, pulp and print', 'Chemical and petrochemical']),
    'End': ProcessGroup(['Construction','Equipment', 'Residential','Transport', 'Commercial and public services', 'Other', 'Losses']),
}

ordering = [['Sources'],['Refineries'],['Utilities'],['Industry'],['End']]

Sources_Partitioned = Partition.Simple('process',['Coal','Gas','Crude Oil','Renewable','Solid biomass & waste', 'Minerals', 'Scrap','Other Materials'])
Industry_Partitioned = Partition.Simple('process',['Chemical and petrochemical','Iron and steel', 'Non-ferrous metals', 'Paper, pulp and print' ])
End_Partitioned = Partition.Simple('process',['Construction', 'Residential','Equipment','Transport','Commercial and public services', 'Other',  'Losses'])

nodes['Sources'].partition = Sources_Partitioned
nodes['End'].partition = End_Partitioned

bundles = [
    Bundle('Sources', 'Refineries'),
    Bundle('Sources', 'Utilities'),
    Bundle('Sources','Industry'),
    Bundle('Sources','End'),
    Bundle('Refineries', 'Utilities'),
    Bundle('Refineries', 'Industry'),
    Bundle('Refineries', 'End'),
    Bundle('Utilities', 'Industry'),
    Bundle('Utilities','Refineries'),
    Bundle('Utilities','End'),
    Bundle('Industry','End'),
]

Types_Partitioned = Partition.Simple('type', np.unique(flows['type']))
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition = Types_Partitioned)
weave(sdd, flows, palette = 'Paired_12').to_widget(**size)

**Comment by ricklupton** [comment]
Thanks for the detailed report with pictures and code!

There's a recent fix in commit 2531886 for node directions. Please can you try upgrading to v2.0.0a3 (`pip install --upgrade --no-deps floweaver`) and see if that helps?

I've also added a brief example in the docs about how you might want a waypoint to help with this -- suggestions welcome if it's not clear: http://floweaver.readthedocs.io/en/latest/cookbook/forwards-backwards.html

**Comment by jfouillou** [comment]
Hello,

Yes, the update did the trick! Here's a screenshot of what it looks like now without any change to the code (there was no need to add aditional waypoints). Thanks again

![screenshot3](https://user-images.githubusercontent.com/20640418/36506256-ff9920a2-174d-11e8-8d14-17ecaea21fd2.png)

**Comment by ricklupton** [comment]
Great, glad it's working for you.
