### ISSUE TITLE
Error: weave(sdd, flows).to_widget(**size) 

### ISSUE THREAD

**Issue by 3mlifamily** [ricklupton/floweaver#90]
The following statement prompted error:

weave(sdd, flows).to_widget(**size)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-cc3f35338055> in <module>
----> 1 weave(sdd, flows).to_widget(**size)

~\AppData\Local\Continuum\anaconda3\envs\venv_pandas\lib\site-packages\floweaver\weave.py in weave(sankey_definition, dataset, measures, link_width, link_color, palette)
     31 
     32     # Calculate the view graph (adding dummy nodes)
---> 33     GV = view_graph(sankey_definition)
     34 
     35     # Add implicit to/from Elsewhere bundles to the view definition to ensure

~\AppData\Local\Continuum\anaconda3\envs\venv_pandas\lib\site-packages\floweaver\view_graph.py in view_graph(sankey_definition)
     13     G.ordering = sankey_definition.ordering
     14     G = _add_bundles_to_graph(G, sankey_definition.bundles,
---> 15                               _bundle_order(sankey_definition))
     16 
     17     return G

~\AppData\Local\Continuum\anaconda3\envs\venv_pandas\lib\site-packages\floweaver\view_graph.py in _add_bundles_to_graph(G, bundles, sort_key)
     25             # everywhere!
     26             if a is not Elsewhere and b is not Elsewhere:
---> 27                 G = add_dummy_nodes(G, a, b, k, _dummy_kw(bundle))
     28 
     29     # check flow partitions are compatible

~\AppData\Local\Continuum\anaconda3\envs\venv_pandas\lib\site-packages\floweaver\dummy_nodes.py in add_dummy_nodes(G, v, w, bundle_key, node_kwargs, dummy_key)
     32         dummy_key = '{}_{}'.format(v, w)
     33 
---> 34     V = G.get_node(v)
     35     W = G.get_node(w)
     36     H = G.copy()

~\AppData\Local\Continuum\anaconda3\envs\venv_pandas\lib\site-packages\floweaver\layered_graph.py in get_node(self, u)
     20     def get_node(self, u):
     21         """Get the ProcessGroup or Waypoint associated with `u`"""
---> 22         return self.node[u]['node']
     23 
     24 

**AttributeError: 'LayeredGraph' object has no attribute 'node'**

**Comment by 3mlifamily** [comment]
The statements before are running fine:
#-------------- Python Code  -------------------------
import pandas as pd
flows = pd.read_csv('simple_fruit_sales.csv')

from ipysankeywidget import SankeyWidget
SankeyWidget(links=flows.to_dict('records'))

from floweaver import *
# Set the default size to fit the documentation better.
size = dict(width=570, height=300)
nodes = {
'farms': ProcessGroup(['farm1', 'farm2', 'farm3','farm4', 'farm5', 'farm6']),
'customers': ProcessGroup(['James', 'Mary', 'Fred', 'Susan']),
}

ordering = [
['farms'], # put "farms" on the left...
['customers'], # ... and "customers" on the right.
]

bundles = [
Bundle('farms', 'customers'),
]

sdd = SankeyDefinition(nodes, bundles, ordering)

#-------
weave(sdd, flows).to_widget(**size)  ## **<----- This line gives error**

**Comment by jfoster17** [comment]
Might be due to a networkx version incompatibility? With networkx==2.1 I got this error on that line:

`AttributeError: 'DiGraph' object has no attribute 'ordering'`

Which was fixed by upgrading to networkx==2.3

**Comment by jAchtzehn** [comment]
I am having the same issue. Seems to be related to networkx 2.4. Downgrade to 2.3 and it should work!

**Comment by ricklupton** [comment]
The latest version *2.0.0a6* should be compatible with networkx 2.4 now.

Fixed in 393defb49fb35184bc65e35687f609853d876b48

**Comment by ricklupton** [comment]
P.S thanks all for reporting the error
