### ISSUE TITLE
absolute flow thickness

### ISSUE THREAD

**Issue by francescodallalonga** [ricklupton/floweaver#94]
Dear Rick,
 
I just started using floweaver to visualize energy flows resusulting from an energy model. It’s brilliant and I absolutely love it!!
There’s one thing I’ve been struggling with, and I can’t find information about it in the tutorials or elsewhere. I would like to assign an “absolute thickness” to the flows, so that I can compare how the flow diagrams change from one year to the next.
So, for example, say that I have the following minimalistic table:

year | source | target | value
-- | -- | -- | --
2020 | A | B | 10
2025 | A | B | 20

If I now make two separate flow diagrams for 2020 and 2025 they will look exactly the same. I would like to make them such that the A->B flow-line in 2025 is twice as thick as in 2020. Is it possible?

Thnaks a lot! 
Best regards, 
Francesco

**Comment by ricklupton** [comment]
Hi Francesco, thanks for reposting this here.

The answer is to set the scale for the widget to a consistent value, like this:

```
w1 = weave(sdd, flows.query('year == 2020')).to_widget(**size)
w1.scale = SCALE
w1
```

I'll add a cookbook example to the docs showing this.

**Comment by ricklupton** [comment]
See here: https://floweaver.readthedocs.io/en/latest/cookbook/scale.html

**Comment by francescodallalonga** [comment]
Thanks a lot Rick, it works like a charm!
